#!/usr/bin/env python3  
# The shebang above tells the operating system to use Python 3 as the interpreter for this script.

"""
----------------------------------------------------------------------------------------------------
Script Name: data_logger.py
Version: 1.0
Author: Michael Du Preez
Date: 2025-03-18

Overview:
    This script continuously scans a specified log directory (default: ~/wardrivelog) for two specific 
    log files: "data.bettercap" and "data.kismet". These files are generated by separate logging 
    processes for bettercap and kismet, respectively. The script parses data from both files and merges 
    them into a single CSV file. The merged CSV file is created once at startup (named "wardrive-<todaysdateandtime>.csv")
    and is continuously updated with merged data.

    At startup, the script checks for an "upload" subdirectory in the log directory. If it does not exist, 
    the script creates it. Then, any preexisting .csv files in the log directory are moved into the "upload" 
    directory with appropriate log messages.

    The output CSV file has two header lines (identical to the kismet header):

      WigleWifi-1.4,appRelease=Kismet202307R1,model=Kismet202307R1,release=2023.07.R1,
      device=kismet,display=kismet,board=kismet,brand=kismet
      MAC,SSID,AuthMode,FirstSeen,Channel,RSSI,CurrentLatitude,CurrentLongitude,AltitudeMeters,AccuracyMeters,Type

    For rows from the .bettercap file (with header: RSSI,MAC,Vendor,Flags,Seen):
      - The "RSSI" value is taken (with "dBm" removed).
      - "MAC" is preserved.
      - "Vendor" is mapped to "SSID".
      - "Flags" is mapped to "AuthMode".
      - "Seen" (time only) is prefixed with the date extracted from the filename to form "FirstSeen".
      - The record’s "Type" is set to "BLE".
    If a matching MAC exists in the .kismet file, its GPS-related fields are merged; otherwise, for BLE 
    records missing GPS data, the script uses the most recent kismet record with valid GPS data as a fallback.

    Every 10 iterations the script logs a summary showing cumulative changes (new records and updates)
    since the last summary log.

Usage:
    To run the script, execute the following command in your terminal:
        python3 data_logger.py --log-dir ~/wardrivelog

Prerequisites:
    - Python 3.x must be installed on your system.
    - The log directory should contain at least one "data.bettercap" file and one "data.kismet" file.
----------------------------------------------------------------------------------------------------
"""

# Import modules needed for file system operations, pattern matching, CSV processing, etc.
import os                  # Provides functions for interacting with the operating system.
import glob                # Used for finding files matching a specified pattern.
import csv                 # Provides functions for reading and writing CSV (Comma Separated Values) files.
import argparse            # Facilitates parsing command-line arguments.
import logging             # Provides a flexible framework for emitting log messages.
import signal              # Enables handling of termination signals.
import sys                 # Provides access to system-specific functions, such as exiting the program.
import re                  # Provides regular expression matching operations.
from datetime import datetime  # Provides classes for manipulating dates and times.
import copy                # Used for creating copies of dictionaries.
import shutil              # Provides high-level file operations like moving files.

# -----------------------------------------------------------------------------
# Global Constants & Logging Configuration
# -----------------------------------------------------------------------------

# Define header lines for the merged CSV file; these are the same as the kismet header.
HEADER_LINE_1 = ("WigleWifi-1.4,appRelease=Kismet202307R1,model=Kismet202307R1,"
                 "release=2023.07.R1,device=kismet,display=kismet,board=kismet,brand=kismet")
HEADER_LINE_2 = ("MAC,SSID,AuthMode,FirstSeen,Channel,RSSI,CurrentLatitude,"
                 "CurrentLongitude,AltitudeMeters,AccuracyMeters,Type")

# Define the list of columns for the output CSV file.
OUTPUT_COLUMNS = ["MAC", "SSID", "AuthMode", "FirstSeen", "Channel", "RSSI",
                  "CurrentLatitude", "CurrentLongitude", "AltitudeMeters", "AccuracyMeters", "Type"]

# Define ANSI color codes for a green prefix in log messages.
MERGE_GREEN = "\x1b[32m"  # ANSI escape code for green text.
RESET = "\x1b[0m"         # ANSI escape code to reset text formatting.

# Configure the logging module to output messages with a green [MERGE] prefix.
logging.basicConfig(
    level=logging.INFO,  # Set default logging level to INFO.
    format=f"{MERGE_GREEN}[MERGE]{RESET} %(asctime)s [%(levelname)s] %(message)s",  # Log message format.
    datefmt="%Y-%m-%d %H:%M:%S"  # Date/time format for log messages.
)

# -----------------------------------------------------------------------------
# Signal Handler for Graceful Shutdown
# -----------------------------------------------------------------------------

def signal_handler(sig, frame):
    """
    Handle termination signals (e.g., SIGINT, SIGTERM) to allow for a graceful shutdown of the merge loop.
    
    Parameters:
        sig: The signal number.
        frame: The current stack frame (unused in this handler).
    """
    logging.info("Shutdown signal received. Exiting merge loop...")  # Log the shutdown event.
    sys.exit(0)  # Exit the program.

# Register the signal_handler function for SIGINT and SIGTERM.
signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)

# -----------------------------------------------------------------------------
# Pre-startup Function: check_and_move_csv_files
# -----------------------------------------------------------------------------

def check_and_move_csv_files(log_dir: str, upload_dir: str) -> None:
    """
    Check if the "upload" subdirectory exists in the log directory; if not, create it.
    Then, move any preexisting .csv files from the log directory to the upload directory.
    Log all actions accordingly.
    
    Args:
        log_dir (str): The main log directory.
        upload_dir (str): The subdirectory designated for uploads.
    """
    # If the upload directory does not exist, create it.
    if not os.path.isdir(upload_dir):
        try:
            os.makedirs(upload_dir)  # Create the directory.
            logging.info("Upload directory created: %s", upload_dir)  # Log successful creation.
        except Exception as e:
            logging.error("Error creating upload directory %s: %s", upload_dir, e, exc_info=True)
    
    # Use glob to find all .csv files in the top level of the log directory.
    csv_files = glob.glob(os.path.join(log_dir, "*.csv"))
    for file in csv_files:
        # Check if the file is already in the upload directory; if so, skip it.
        if os.path.dirname(file) == os.path.abspath(upload_dir):
            continue
        try:
            shutil.move(file, upload_dir)  # Move the CSV file to the upload directory.
            logging.info("Moved file %s to upload directory.", file)  # Log the file move.
        except Exception as e:
            logging.error("Error moving file %s: %s", file, e, exc_info=True)

# -----------------------------------------------------------------------------
# Helper Function: is_valid_kismet_file
# -----------------------------------------------------------------------------

def is_valid_kismet_file(filepath: str) -> bool:
    """
    Check if a given kismet file's basename matches the expected date-time format.
    The expected format is: YYYY-MM-DD_HH-MM-SS.kismet.
    Files like 'wardrive.kismet' are ignored.
    
    Parameters:
        filepath (str): Full path to the file.
        
    Returns:
        bool: True if the file name matches the pattern, False otherwise.
    """
    basename = os.path.basename(filepath)  # Get the file name without directory components.
    pattern = r"^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.kismet$"  # Regular expression pattern.
    return re.match(pattern, basename) is not None  # Return True if the pattern matches.

# -----------------------------------------------------------------------------
# Function: get_newest_file
# -----------------------------------------------------------------------------

def get_newest_file(directory: str, extension: str) -> str:
    """
    Search the given directory for a file with the specified extension.
    Now, instead of scanning for timestamped files, this function explicitly looks for a file 
    named "data.<extension>" (e.g., "data.bettercap" or "data.kismet"). If such a file exists, 
    it is returned. If not, the function falls back to scanning for files matching a pattern.
    
    Args:
        directory (str): Directory to search.
        extension (str): File extension (e.g., "bettercap" or "kismet").
    
    Returns:
        str: Full path to the file found, or an empty string if none exists.
    """
    # Build the explicit filename based on the extension.
    explicit_filename = os.path.join(directory, f"data.{extension}")
    if os.path.exists(explicit_filename):
        logging.debug("Found explicit file: %s", explicit_filename)  # Log that the explicit file was found.
        return explicit_filename  # Return the explicit file.
    
    # If the explicit file is not found, fall back to scanning for files with the given extension.
    pattern = os.path.join(directory, f"*.{extension}")
    files = glob.glob(pattern)
    # For kismet files, further filter files that match the expected date-time pattern.
    if extension == "kismet":
        files = [f for f in files if is_valid_kismet_file(f)]
    if not files:
        return ""  # Return an empty string if no files are found.
    files.sort()  # Sort the list of files.
    newest = files[-1]  # Take the last file (newest based on filename sort).
    logging.debug("Found newest .%s file by fallback: %s", extension, newest)
    return newest  # Return the fallback file.

# -----------------------------------------------------------------------------
# Function: parse_bettercap_file
# -----------------------------------------------------------------------------

def parse_bettercap_file(filepath: str, base_date: str) -> dict:
    """
    Parse the .bettercap file and return a dictionary keyed by MAC address.
    The file is expected to have a header line: RSSI,MAC,Vendor,Flags,Seen.
    Extra commas in the Vendor or Flags fields are handled.
    The "dBm" unit is removed from the RSSI field.
    The "Seen" time (HH:MM:SS) is prefixed with the base_date to form a full timestamp ("YYYY-MM-DD HH:MM:SS").
    
    Args:
        filepath (str): Path to the .bettercap file.
        base_date (str): Date string (YYYY-MM-DD) extracted from the filename.
    
    Returns:
        dict: Dictionary with MAC addresses as keys and mapped records as values.
    """
    data = {}  # Initialize an empty dictionary to store parsed records.
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()  # Read the file line by line.
    except Exception as e:
        logging.error("Error reading %s: %s", filepath, e, exc_info=True)
        return data  # Return empty dictionary if file reading fails.

    # Loop over each line after the header.
    for line in lines[1:]:
        if not line.strip():
            continue  # Skip empty lines.
        parts = [p.strip() for p in line.split(",")]  # Split the line by commas and trim whitespace.
        rssi = mac = vendor = flags = seen = ""  # Initialize variables.
        if len(parts) == 5:
            rssi, mac, vendor, flags, seen = parts  # Expected 5 parts.
        elif len(parts) == 7:
            rssi = parts[0]
            mac = parts[1]
            vendor = parts[2] + ", " + parts[3]
            flags = parts[4] + ", " + parts[5]
            seen = parts[6]
        elif len(parts) > 7:
            rssi = parts[0]
            mac = parts[1]
            seen = parts[-1]
            middle = parts[2:-1]
            half = len(middle) // 2
            vendor = ", ".join(middle[:half])
            flags = ", ".join(middle[half:])
        else:
            continue  # Skip lines that don't match expected formats.

        rssi = rssi.replace("dBm", "").strip()  # Remove "dBm" from the RSSI value.
        full_timestamp = f"{base_date} {seen}"  # Combine base_date with the seen time.
        # Create a record mapping fields from bettercap to output CSV fields.
        record = {
            "MAC": mac,
            "SSID": vendor,       # Map Vendor to SSID.
            "AuthMode": flags,    # Map Flags to AuthMode.
            "FirstSeen": full_timestamp,  # Combined date and time.
            "Channel": "",
            "RSSI": rssi,
            "CurrentLatitude": "",
            "CurrentLongitude": "",
            "AltitudeMeters": "",
            "AccuracyMeters": "",
            "Type": ""            # Will be set to "BLE" later.
        }
        data[mac] = record  # Store the record using the MAC address as key.
    return data  # Return the dictionary of parsed records.

# -----------------------------------------------------------------------------
# Function: parse_kismet_file
# -----------------------------------------------------------------------------

def parse_kismet_file(filepath: str) -> dict:
    """
    Parse the .kismet file and return a dictionary keyed by MAC address.
    The file is expected to have two header lines; the second header defines the columns:
    MAC,SSID,AuthMode,FirstSeen,Channel,RSSI,CurrentLatitude,CurrentLongitude,AltitudeMeters,AccuracyMeters,Type.
    
    Args:
        filepath (str): Path to the .kismet file.
    
    Returns:
        dict: Dictionary with MAC addresses as keys and corresponding records as values.
    """
    data = {}  # Initialize an empty dictionary to store parsed kismet records.
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)  # Create a CSV reader.
            _ = next(reader, None)  # Skip the first header line.
            header2 = next(reader, None)  # Read the second header line.
            if not header2:
                logging.error("No valid header found in %s.", filepath)
                return data
            # Process each subsequent row.
            for row in reader:
                if not row or len(row) < len(OUTPUT_COLUMNS):
                    continue  # Skip rows that are empty or incomplete.
                record = dict(zip(OUTPUT_COLUMNS, row))  # Map each column header to the row value.
                mac = record.get("MAC", "")  # Get the MAC address.
                if mac:
                    data[mac] = record  # Store the record keyed by MAC.
    except Exception as e:
        logging.error("Error reading %s: %s", filepath, e, exc_info=True)
    return data  # Return the dictionary of parsed records.

# -----------------------------------------------------------------------------
# Function: merge_logs
# -----------------------------------------------------------------------------

def merge_logs(bettercap_data: dict, kismet_data: dict) -> dict:
    """
    Merge the dictionaries from bettercap and kismet files (keyed by MAC address).
    For each MAC:
      - If a kismet record exists, its GPS and channel fields are retained.
      - The bettercap record supplies SSID, AuthMode, FirstSeen, and RSSI.
      - For BLE records, the "Type" field is set to "BLE".
      - If BLE records lack GPS data, use the most recent kismet record with valid GPS data as a fallback.
    
    Args:
        bettercap_data (dict): Parsed records from the .bettercap file.
        kismet_data (dict): Parsed records from the .kismet file.
    
    Returns:
        dict: Merged dictionary with MAC addresses as keys.
    """
    merged = {}  # Initialize the merged dictionary.
    # First, copy all kismet records into the merged dictionary.
    for mac, record in kismet_data.items():
        merged[mac] = record

    # Then, update or add records from the bettercap data.
    for mac, bc_record in bettercap_data.items():
        if mac in merged:
            merged[mac]["SSID"] = bc_record.get("SSID", merged[mac]["SSID"])
            merged[mac]["AuthMode"] = bc_record.get("AuthMode", merged[mac]["AuthMode"])
            merged[mac]["FirstSeen"] = bc_record.get("FirstSeen", merged[mac]["FirstSeen"])
            merged[mac]["RSSI"] = bc_record.get("RSSI", merged[mac]["RSSI"])
        else:
            merged[mac] = bc_record
        merged[mac]["Type"] = "BLE"  # Mark this record as coming from BLE.

    # Find a fallback kismet record with valid GPS data.
    fallback_gps = None
    fallback_gps_time = None
    for record in kismet_data.values():
        if record.get("CurrentLatitude", "").strip() and record.get("CurrentLongitude", "").strip():
            try:
                t = datetime.strptime(record["FirstSeen"], "%Y-%m-%d %H:%M:%S")
            except Exception:
                continue
            if fallback_gps is None or t > fallback_gps_time:
                fallback_gps = record
                fallback_gps_time = t

    # For BLE records missing GPS data, fill in with fallback GPS information.
    if fallback_gps:
        for rec in merged.values():
            if rec.get("Type") == "BLE":
                if not rec.get("Channel", "").strip() or not rec.get("CurrentLatitude", "").strip():
                    rec["Channel"] = fallback_gps.get("Channel", "")
                    rec["CurrentLatitude"] = fallback_gps.get("CurrentLatitude", "")
                    rec["CurrentLongitude"] = fallback_gps.get("CurrentLongitude", "")
                    rec["AltitudeMeters"] = fallback_gps.get("AltitudeMeters", "")
                    rec["AccuracyMeters"] = fallback_gps.get("AccuracyMeters", "")
    return merged  # Return the merged dictionary.

# -----------------------------------------------------------------------------
# Function: write_merged_csv
# -----------------------------------------------------------------------------

def write_merged_csv(merged_data: dict, output_filepath: str) -> None:
    """
    Write the merged data to the output CSV file with two header lines.
    Records are sorted by the 'FirstSeen' field.
    
    Args:
        merged_data (dict): Merged records keyed by MAC address.
        output_filepath (str): Full path to the output CSV file.
    """
    try:
        with open(output_filepath, "w", newline="", encoding="utf-8") as f:
            f.write(HEADER_LINE_1 + "\n")  # Write the first header line.
            f.write(HEADER_LINE_2 + "\n")  # Write the second header line.
            writer = csv.writer(f)  # Create a CSV writer.
            # Sort the records by the "FirstSeen" field.
            sorted_records = sorted(merged_data.values(), key=lambda r: r.get("FirstSeen", ""))
            for record in sorted_records:
                # Create a row by extracting values for each output column.
                row = [record.get(col, "") for col in OUTPUT_COLUMNS]
                writer.writerow(row)  # Write the row to the CSV file.
        logging.debug("Merged CSV file updated: %s", output_filepath)
    except Exception as e:
        logging.error("Error writing merged CSV file %s: %s", output_filepath, e, exc_info=True)

# -----------------------------------------------------------------------------
# Main Loop: Continuously update merged CSV file and log summary every 10 iterations
# -----------------------------------------------------------------------------

def main():
    """
    Main function that orchestrates the merging process:
      1. Parse command-line arguments.
      2. Expand the log directory path and verify its existence.
      3. Check for and move any preexisting CSV files to an "upload" subdirectory.
      4. Continuously monitor the log directory for the "data.bettercap" and "data.kismet" files,
         parse and merge their data, and update the merged CSV file.
      5. Every 10 iterations, log a summary of cumulative changes since the last summary.
    """
    # Parse command-line arguments.
    parser = argparse.ArgumentParser(
        description="Continuously merge data from data.bettercap and data.kismet log files into one CSV."
    )
    parser.add_argument("--log-dir", type=str, default="~/wardrivelog",
                        help="Directory containing wardriving log files (default: ~/wardrivelog)")
    args = parser.parse_args()  # Retrieve the parsed arguments.

    # Expand the log directory path (e.g., convert "~" to the full home directory path).
    log_dir = os.path.expanduser(args.log_dir)
    if not os.path.isdir(log_dir):
        logging.error("Log directory '%s' does not exist.", log_dir)
        sys.exit(1)

    # Define the upload subdirectory path and check/move preexisting CSV files.
    upload_dir = os.path.join(log_dir, "upload")
    check_and_move_csv_files(log_dir, upload_dir)

    logging.info("Merge process started. Monitoring log directory: %s", log_dir)

    # Create an output CSV file name with a timestamp (for the merged output).
    now_str = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    output_filename = f"wardrive-{now_str}.csv"
    output_filepath = os.path.join(log_dir, output_filename)
    logging.info("Output CSV file: %s", output_filepath)

    # Maintain a snapshot of merged data from the last summary log.
    last_summary_data = {}
    summary_interval = 10  # Set summary log interval (every 10 iterations).

    iteration = 0  # Initialize the iteration counter.
    waiting_counter = 0  # Initialize a counter for waiting if files are not found.
    # Begin the infinite loop to continuously merge data.
    while True:
        iteration += 1  # Increment the iteration counter.
        try:
            # Explicitly look for the "data.bettercap" file.
            bettercap_file = get_newest_file(log_dir, "bettercap")
            # Explicitly look for the "data.kismet" file.
            kismet_file = get_newest_file(log_dir, "kismet")
            # If either file is not found, log a waiting message periodically and continue.
            if not (bettercap_file and kismet_file):
                waiting_counter += 1
                if waiting_counter % 5 == 0:
                    logging.info("Still waiting for data.bettercap and data.kismet files in %s.", log_dir)
                import time
                time.sleep(1)
                continue
            else:
                waiting_counter = 0  # Reset waiting counter if both files are found.

            # Extract the base date from the bettercap filename.
            base_date_match = re.match(r"(\d{4}-\d{2}-\d{2})_", os.path.basename(bettercap_file))
            base_date = base_date_match.group(1) if base_date_match else ""
            # Parse data from the bettercap file.
            bettercap_data = parse_bettercap_file(bettercap_file, base_date)
            # Parse data from the kismet file.
            kismet_data = parse_kismet_file(kismet_file)
            # Merge the parsed data.
            merged_data = merge_logs(bettercap_data, kismet_data)
            # Write the merged data to the output CSV file.
            write_merged_csv(merged_data, output_filepath)

            # Every 'summary_interval' iterations, compute and log cumulative changes.
            if iteration % summary_interval == 0:
                new_lines = 0
                updates = 0
                if not last_summary_data:
                    new_lines = len(merged_data)
                else:
                    for mac, record in merged_data.items():
                        if mac not in last_summary_data:
                            new_lines += 1
                        else:
                            if record != last_summary_data[mac]:
                                updates += 1
                logging.info("Iteration #%d: merged CSV file updated. New lines: %d, Updates: %d",
                             iteration, new_lines, updates)
                # Update the snapshot of the merged data.
                last_summary_data = {k: record.copy() for k, record in merged_data.items()}
        except Exception as e:
            logging.error("Unexpected error during merge iteration %d: %s", iteration, e, exc_info=True)

        try:
            import time
            time.sleep(1)  # Wait for 1 second before the next iteration.
        except KeyboardInterrupt:
            logging.info("Keyboard interrupt received. Exiting merge loop.")
            break  # Exit the loop if a keyboard interrupt is detected.

if __name__ == "__main__":
    main()  # Run the main function when the script is executed directly.
